"""Root CLI group for remo."""

from __future__ import annotations

import sys

import click

import remo_cli
from remo_cli.core.completion import SHELLS


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(
    version=remo_cli.__version__, prog_name="remo", message="%(prog)s %(version)s"
)
def cli() -> None:
    """Remote development environment CLI."""


@cli.result_callback()
@click.pass_context
def _post_command_hook(ctx: click.Context, result: object, **kwargs: object) -> None:
    """Run passive update and completion-staleness checks after every command."""
    try:
        from remo_cli.core.version import check_for_updates_passive
        from remo_cli.core.output import print_info

        hint = check_for_updates_passive()
        if hint:
            print()
            print_info(hint)

        stale_hint = _stale_completion_hint(ctx)
        if stale_hint:
            print()
            print_info(stale_hint)
    except Exception:
        pass


def _stale_completion_hint(ctx: click.Context) -> str | None:
    """Nudge when the installed completion script predates the running remo.

    remo cannot report this from inside the failing shell — the shell parses
    the activation script itself, so there is no remo process running when it
    breaks. Noticing here, on a command the user ran deliberately, is the only
    place remo gets to say anything at all.

    Silent unless a script is actually installed: someone who never opted into
    completion should not be nagged toward it.
    """
    if ctx.invoked_subcommand == "completion":
        return None

    from remo_cli.core.completion import stale_shells

    # Scans installed scripts instead of detecting the current shell: this runs
    # after *every* command, and detect_shell() now walks the process tree.
    stale = stale_shells(remo_cli.__version__)
    if not stale:
        return None
    return (
        f"Your {', '.join(stale)} completion script was generated by an older "
        f"remo. Refresh it with: remo completion install {stale[0]}"
    )


# Substitutions applied to Click's fish activation script.
#
# Each pair MUST match exactly once. `tests/unit/cli/test_completion.py` pins
# that, because `str.replace` fails open: if a Click upgrade reflows the
# template, every substitution below silently becomes a no-op and we ship the
# unpatched script — which is precisely the bug each one exists to prevent.
FISH_HARDENING: tuple[tuple[str, str], ...] = (
    # Click's completion handler emits a bare newline when there are no
    # matches (e.g. `remo upd<TAB>` — no such command). fish expands an
    # unquoted empty variable to *zero* arguments, so `string split ","
    # $completion` degrades to a one-argument call and fails with
    # "string split: missing argument". Skip empty candidates outright.
    (
        "for completion in $response;\n        set -l metadata",
        "for completion in $response;\n"
        '        if test -z "$completion";\n'
        "            continue;\n"
        "        end;\n"
        "        set -l metadata",
    ),
    # Quote the metadata expansions. Unquoted, any candidate that leaves
    # $metadata[1] empty makes fish see `test = dir` and report "test: Missing
    # argument at index 3" — once per candidate, per keypress, which is how a
    # single malformed entry becomes a screenful. Quoted, the comparison is
    # merely false and completion degrades to "no suggestions". The guard
    # above already covers the known trigger; this bounds the blast radius of
    # the next one.
    ('if test $metadata[1] = "dir";', 'if test "$metadata[1]" = "dir";'),
    ('else if test $metadata[1] = "file";', 'else if test "$metadata[1]" = "file";'),
    ('else if test $metadata[1] = "plain";', 'else if test "$metadata[1]" = "plain";'),
)


def harden_fish_source(source: str) -> str:
    """Apply FISH_HARDENING to Click's generated fish activation script."""
    for old, new in FISH_HARDENING:
        source = source.replace(old, new)
    return source


def completion_header(shell: str) -> str:
    """Version stamp identifying which remo generated an activation script.

    The script is a static snapshot: upgrading remo does not rewrite a file
    the user already generated, and remo cannot detect the staleness from
    inside the failing shell — fish parses the file itself, so there is no
    remo process running to report anything. Stamping the version is the
    cheapest way to make "is this stale?" answerable by looking at the file.
    """
    return (
        f"# remo shell completion for {shell} "
        f"— generated by remo {remo_cli.__version__}.\n"
        f"# Do not edit. Regenerate after upgrading remo:\n"
        f"#     remo completion install {shell}\n"
    )


def render_completion_script(shell: str) -> str:
    """Build the full activation script for SHELL: version stamp + source."""
    from click.shell_completion import get_completion_class

    completer_cls = get_completion_class(shell)
    if completer_cls is None:
        raise click.ClickException(f"Unsupported shell: {shell}")

    ctx = click.get_current_context()
    instance = completer_cls(ctx.find_root().command, {}, "remo", "_REMO_COMPLETE")
    source = instance.source()

    if shell == "fish":
        source = harden_fish_source(source)

    return completion_header(shell) + source


class _CompletionGroup(click.Group):
    """Group that keeps bare ``remo completion <shell>`` working as ``show``.

    The bare spelling predates the group split and is what every existing
    README, blog post, and shell history contains. Breaking it would strand
    users in the one release where they already have to regenerate (3.0.0
    renames commands), so the old form is routed rather than removed.
    """

    def resolve_command(  # type: ignore[override]
        self, ctx: click.Context, args: list[str]
    ) -> tuple[str | None, click.Command | None, list[str]]:
        if args and args[0] in SHELLS:
            args = ["show", *args]
        return super().resolve_command(ctx, args)


@cli.group(cls=_CompletionGroup)
def completion() -> None:
    """Manage tab completion for bash, zsh, and fish.

    Most people want:

        remo completion install

    which detects your shell, writes the activation script, and (for bash and
    zsh) offers to add the one line that loads it.
    """


@completion.command("show")
@click.argument("shell", type=click.Choice(SHELLS))
def completion_show(shell: str) -> None:
    """Print the activation script for SHELL to stdout.

    Useful for inspecting what `install` would write, or for wiring completion
    up by hand. Prefer `remo completion install`, which is idempotent and
    re-runnable; redirecting this into an rc file with `>>` is not.
    """
    click.echo(render_completion_script(shell))


@completion.command("install")
@click.argument("shell", type=click.Choice(SHELLS), required=False)
@click.option(
    "--yes",
    "-y",
    is_flag=True,
    help="Add the rc `source` line without prompting (bash and zsh only).",
)
def completion_install(shell: str | None, yes: bool) -> None:
    """Install tab completion for SHELL (auto-detected if omitted).

    Detection prefers the shell you are actually running, read from the process
    tree, and falls back to $SHELL. The two disagree more often than you would
    expect — macOS ships zsh as the login shell, so $SHELL says zsh even when
    you launch fish from your terminal emulator. When they differ remo says so
    and uses the shell you are typing into; naming one explicitly always wins.

    Writes the activation script to its own file and, for bash and zsh, adds a
    single line to your rc file that loads it. Safe to re-run: an unchanged
    script and an already-present rc line are both no-ops, so this is also how
    you refresh completion after upgrading remo.

    fish needs no rc change — its completions directory is loaded
    automatically.
    """
    from remo_cli.core.completion import (
        detect_shell,
        fish_autoload_problem,
        install,
    )
    from remo_cli.core.output import print_info, print_success, print_warning

    if shell is None:
        detected = detect_shell()
        if detected.shell is None:
            raise click.ClickException(
                "Could not determine which shell you are using. "
                f"Pass one explicitly: remo completion install [{'|'.join(SHELLS)}]"
            )
        shell = detected.shell
        print_info(f"Detected shell: {shell} (from {detected.source})")
        if detected.conflict:
            # Silently picking one is how this went wrong before: a macOS fish
            # user got zsh completion installed, with a success message.
            print_warning(
                f"$SHELL says {detected.conflict}, but you appear to be running "
                f"{shell}. Installing for {shell} — pass a shell name explicitly "
                "to override."
            )

    outcome = install(shell, render_completion_script(shell) + "\n", edit_rc=yes)

    if outcome.script_written:
        print_success(f"Wrote completion script: {outcome.script_path}")
    else:
        print_info(f"Completion script already current: {outcome.script_path}")

    if outcome.rc_path is None:
        # fish needs no rc edit, but "wrote the file" is not the same as "fish
        # will read it" — and when it won't, the failure is completely silent.
        problem = fish_autoload_problem(outcome.script_path)
        if problem:
            print_warning(problem)
            return
        print_info("Start a new shell (or run `exec fish`) to pick it up.")
        return

    if outcome.rc_line_added:
        print_success(f"Added the loader line to {outcome.rc_path}")
        print_info(f"Start a new shell (or run `source {outcome.rc_path}`).")
        return

    if outcome.pending_source_line is None:
        print_info(f"{outcome.rc_path} already loads it — nothing to do.")
        return

    # Deliberately not written without consent: silently editing a dotfile is
    # the kind of thing people are justifiably annoyed to discover later.
    print_warning(f"{outcome.rc_path} does not load the script yet.")
    print_info("Add this line to it, or re-run with --yes to have remo do it:")
    print_info(f"    {outcome.pending_source_line}")


def _register_commands() -> None:
    """Register all subcommands and groups. Called at import time."""
    # Import lazily to avoid circular imports and to keep startup fast
    # when only --version or --help is requested.
    from remo_cli.cli.shell import shell  # noqa: F811
    from remo_cli.cli.cp import cp  # noqa: F811
    from remo_cli.cli.added import add, configure, remove  # noqa: F811
    from remo_cli.cli.providers.factory import build_provider_group  # noqa: F811
    from remo_cli.cli.web import web  # noqa: F811
    from remo_cli.core.provider_registry import all_descriptors  # noqa: F811

    cli.add_command(shell)
    cli.add_command(cp)
    cli.add_command(add)
    cli.add_command(remove)
    cli.add_command(configure)
    for descriptor in all_descriptors():
        cli.add_command(build_provider_group(descriptor))
    cli.add_command(web)


_register_commands()


def main() -> None:
    """Console-script entry point: run the CLI, translating registry accessor
    errors (data-model.md §8) into a plain-language message and exit code 1
    instead of an uncaught traceback (FR-013: the accessor itself never exits).
    """
    from remo_cli.core.registry import RegistryError

    try:
        cli()
    except RegistryError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
