"""Root CLI group for remo."""

from __future__ import annotations

import sys

import click

import remo_cli


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(
    version=remo_cli.__version__, prog_name="remo", message="%(prog)s %(version)s"
)
def cli() -> None:
    """Remote development environment CLI."""


@cli.result_callback()
def _post_command_hook(result: object, **kwargs: object) -> None:
    """Run passive update check after every command."""
    try:
        from remo_cli.core.version import check_for_updates_passive
        from remo_cli.core.output import print_info

        hint = check_for_updates_passive()
        if hint:
            print()
            print_info(hint)
    except Exception:
        pass


# Where each shell's activation script is meant to end up. Used only to make
# the regenerate hint in the header concrete rather than generic.
COMPLETION_TARGETS: dict[str, str] = {
    "bash": ">> ~/.bashrc",
    "zsh": ">> ~/.zshrc",
    "fish": "> ~/.config/fish/completions/remo.fish",
}

# Substitutions applied to Click's fish activation script.
#
# Each pair MUST match exactly once. `tests/unit/cli/test_completion.py` pins
# that, because `str.replace` fails open: if a Click upgrade reflows the
# template, every substitution below silently becomes a no-op and we ship the
# unpatched script — which is precisely the bug each one exists to prevent.
FISH_HARDENING: tuple[tuple[str, str], ...] = (
    # Click's completion handler emits a bare newline when there are no
    # matches (e.g. `remo upd<TAB>` — no such command). fish expands an
    # unquoted empty variable to *zero* arguments, so `string split ","
    # $completion` degrades to a one-argument call and fails with
    # "string split: missing argument". Skip empty candidates outright.
    (
        "for completion in $response;\n        set -l metadata",
        "for completion in $response;\n"
        '        if test -z "$completion";\n'
        "            continue;\n"
        "        end;\n"
        "        set -l metadata",
    ),
    # Quote the metadata expansions. Unquoted, any candidate that leaves
    # $metadata[1] empty makes fish see `test = dir` and report "test: Missing
    # argument at index 3" — once per candidate, per keypress, which is how a
    # single malformed entry becomes a screenful. Quoted, the comparison is
    # merely false and completion degrades to "no suggestions". The guard
    # above already covers the known trigger; this bounds the blast radius of
    # the next one.
    ('if test $metadata[1] = "dir";', 'if test "$metadata[1]" = "dir";'),
    ('else if test $metadata[1] = "file";', 'else if test "$metadata[1]" = "file";'),
    ('else if test $metadata[1] = "plain";', 'else if test "$metadata[1]" = "plain";'),
)


def harden_fish_source(source: str) -> str:
    """Apply FISH_HARDENING to Click's generated fish activation script."""
    for old, new in FISH_HARDENING:
        source = source.replace(old, new)
    return source


def completion_header(shell: str) -> str:
    """Version stamp identifying which remo generated an activation script.

    The script is a static snapshot: upgrading remo does not rewrite a file
    the user already generated, and remo cannot detect the staleness from
    inside the failing shell — fish parses the file itself, so there is no
    remo process running to report anything. Stamping the version is the
    cheapest way to make "is this stale?" answerable by looking at the file.
    """
    return (
        f"# remo shell completion for {shell} "
        f"— generated by remo {remo_cli.__version__}.\n"
        f"# Do not edit. Regenerate after upgrading remo:\n"
        f"#     remo completion {shell} {COMPLETION_TARGETS[shell]}\n"
    )


@cli.command()
@click.argument("shell", type=click.Choice(["bash", "zsh", "fish"]))
def completion(shell: str) -> None:
    """Print the shell-completion activation script for SHELL.

    Add the output to your shell rc file to enable tab completion. For
    bash and zsh:

        remo completion bash >> ~/.bashrc
        remo completion zsh  >> ~/.zshrc

    For fish:

        remo completion fish > ~/.config/fish/completions/remo.fish
    """
    from click.shell_completion import get_completion_class

    completer_cls = get_completion_class(shell)
    if completer_cls is None:
        raise click.ClickException(f"Unsupported shell: {shell}")

    ctx = click.get_current_context()
    instance = completer_cls(ctx.find_root().command, {}, "remo", "_REMO_COMPLETE")
    source = instance.source()

    if shell == "fish":
        source = harden_fish_source(source)

    click.echo(completion_header(shell) + source)


def _register_commands() -> None:
    """Register all subcommands and groups. Called at import time."""
    # Import lazily to avoid circular imports and to keep startup fast
    # when only --version or --help is requested.
    from remo_cli.cli.shell import shell  # noqa: F811
    from remo_cli.cli.cp import cp  # noqa: F811
    from remo_cli.cli.added import add, remove  # noqa: F811
    from remo_cli.cli.providers.factory import build_provider_group  # noqa: F811
    from remo_cli.cli.web import web  # noqa: F811
    from remo_cli.core.provider_registry import all_descriptors  # noqa: F811

    cli.add_command(shell)
    cli.add_command(cp)
    cli.add_command(add)
    cli.add_command(remove)
    for descriptor in all_descriptors():
        cli.add_command(build_provider_group(descriptor))
    cli.add_command(web)


_register_commands()


def main() -> None:
    """Console-script entry point: run the CLI, translating registry accessor
    errors (data-model.md §8) into a plain-language message and exit code 1
    instead of an uncaught traceback (FR-013: the accessor itself never exits).
    """
    from remo_cli.core.registry import RegistryError

    try:
        cli()
    except RegistryError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
