"""Tests for core.completion — layout, detection, install, staleness.

The install path is the one place remo writes to files it does not own
(``~/.bashrc``, ``~/.zshrc``), so the coverage here leans on idempotency and
on never touching an rc file without consent.
"""

from __future__ import annotations

import os

import pytest

from remo_cli.core import completion
from remo_cli.core.completion import (
    SHELLS,
    detect_shell,
    install,
    installed_version,
    is_stale,
    layout_for,
)

SCRIPT = "# remo shell completion for bash — generated by remo 9.9.9.\n_remo() { :; }\n"


@pytest.fixture
def home(tmp_path, monkeypatch):
    """An isolated HOME with REMO_HOME pointed inside it.

    XDG_CONFIG_HOME is cleared so fish paths are deterministic — a developer
    who happens to export it should not get different results than CI.
    """
    monkeypatch.setenv("REMO_HOME", str(tmp_path / ".config" / "remo"))
    monkeypatch.delenv("XDG_CONFIG_HOME", raising=False)
    return tmp_path


# ---------------------------------------------------------------------------
# layout
# ---------------------------------------------------------------------------


class TestLayout:
    def test_fish_honours_xdg_config_home(self, home, monkeypatch, tmp_path):
        """fish resolves its config dir from $XDG_CONFIG_HOME when set. Writing
        to ~/.config/fish anyway puts the script where fish never looks, and
        fish reports that by silently completing filenames — the bug this
        regression-tests, caught by the fish integration job in CI.
        """
        xdg = tmp_path / "xdg"
        monkeypatch.setenv("XDG_CONFIG_HOME", str(xdg))
        layout = layout_for("fish", home=home)
        assert layout.script_path == xdg / "fish" / "completions" / "remo.fish"

    def test_fish_falls_back_to_dot_config_without_xdg(self, home, monkeypatch):
        monkeypatch.delenv("XDG_CONFIG_HOME", raising=False)
        layout = layout_for("fish", home=home)
        assert layout.script_path == home / ".config/fish/completions/remo.fish"

    def test_fish_needs_no_rc_edit(self, home, monkeypatch):
        monkeypatch.delenv("XDG_CONFIG_HOME", raising=False)
        layout = layout_for("fish", home=home)
        assert layout.script_path == home / ".config/fish/completions/remo.fish"
        # fish scans its completions dir natively — editing config.fish would be
        # gratuitous, and the absence of an rc path is what the CLI branches on.
        assert layout.rc_path is None
        assert layout.source_line is None

    @pytest.mark.parametrize(
        ("shell", "rc_name"), [("bash", ".bashrc"), ("zsh", ".zshrc")]
    )
    def test_bash_and_zsh_get_a_dropin_plus_rc_line(self, home, shell, rc_name):
        layout = layout_for(shell, home=home)
        assert layout.script_path.name == f"completion.{shell}"
        assert layout.rc_path == home / rc_name
        assert layout.source_line is not None
        # Absolute path, not ~ or $HOME: REMO_HOME may point elsewhere entirely
        # and a wrong source line fails silently at shell startup.
        assert str(layout.script_path) in layout.source_line

    def test_unknown_shell_rejected(self, home):
        with pytest.raises(ValueError, match="Unsupported shell"):
            layout_for("nushell", home=home)


# ---------------------------------------------------------------------------
# detection
# ---------------------------------------------------------------------------


class TestDetectShell:
    @pytest.fixture
    def no_parent(self, monkeypatch):
        """Make the process-tree walk find nothing, isolating the $SHELL path."""
        monkeypatch.setattr(completion, "_shell_from_parent", lambda: None)

    @pytest.mark.parametrize("shell", SHELLS)
    def test_falls_back_to_env_when_parent_is_not_a_shell(
        self, monkeypatch, no_parent, shell
    ):
        monkeypatch.setenv("SHELL", f"/usr/bin/{shell}")
        d = detect_shell()
        assert (d.shell, d.source, d.conflict) == (shell, "$SHELL", None)

    def test_unset_env_returns_none(self, monkeypatch, no_parent):
        monkeypatch.delenv("SHELL", raising=False)
        assert detect_shell().shell is None

    def test_unsupported_shell_returns_none(self, monkeypatch, no_parent):
        """Returning None (not a guess) is what lets the CLI ask instead of
        writing completion for the wrong shell."""
        monkeypatch.setenv("SHELL", "/usr/bin/nushell")
        assert detect_shell().shell is None

    def test_parent_process_wins_over_env(self, monkeypatch):
        """The macOS case that motivated this: zsh is the login shell, but the
        user is typing into fish. $SHELL alone confidently installs zsh
        completion for a fish user and reports success."""
        monkeypatch.setattr(completion, "_shell_from_parent", lambda: "fish")
        monkeypatch.setenv("SHELL", "/bin/zsh")
        d = detect_shell()
        assert d.shell == "fish"
        assert d.source == "parent process"
        # Reported, not silently resolved — the CLI turns this into a warning.
        assert d.conflict == "zsh"

    def test_no_conflict_reported_when_both_agree(self, monkeypatch):
        monkeypatch.setattr(completion, "_shell_from_parent", lambda: "fish")
        monkeypatch.setenv("SHELL", "/usr/bin/fish")
        assert detect_shell().conflict is None

    def test_no_conflict_reported_when_env_is_unusable(self, monkeypatch):
        """An unset or exotic $SHELL is not a disagreement worth warning about."""
        monkeypatch.setattr(completion, "_shell_from_parent", lambda: "fish")
        monkeypatch.setenv("SHELL", "/usr/bin/nushell")
        assert detect_shell().conflict is None


class TestShellFromParent:
    def test_walks_past_non_shell_ancestors(self, monkeypatch):
        """Console-script shims and `uv tool` wrappers sit between remo and the
        shell, so checking only the immediate parent finds nothing."""
        tree = {100: ("python", 99), 99: ("remo", 98), 98: ("-fish", 1)}

        def fake_ps(pid, field):
            if pid not in tree:
                return None
            comm, ppid = tree[pid]
            return comm if field == "comm=" else str(ppid)

        monkeypatch.setattr(os, "getppid", lambda: 100)
        monkeypatch.setattr(completion, "_ps_field", fake_ps)
        # "-fish" is how a login shell appears in ps; the dash must not defeat
        # the match.
        assert completion._shell_from_parent() == "fish"

    def test_gives_up_rather_than_looping(self, monkeypatch):
        monkeypatch.setattr(os, "getppid", lambda: 5)
        monkeypatch.setattr(
            completion,
            "_ps_field",
            lambda pid, field: "someproc" if field == "comm=" else "5",
        )
        assert completion._shell_from_parent(max_depth=3) is None

    def test_ps_failure_is_not_fatal(self, monkeypatch):
        """ps is absent or restricted in some containers; falling back to
        $SHELL is correct there, crashing is not."""
        monkeypatch.setattr(os, "getppid", lambda: 100)
        monkeypatch.setattr(completion, "_ps_field", lambda pid, field: None)
        assert completion._shell_from_parent() is None


class TestStaleShells:
    def test_reports_every_stale_shell(self, home):
        install("bash", SCRIPT, edit_rc=False, home=home)
        install("fish", SCRIPT, edit_rc=False, home=home)
        assert completion.stale_shells("10.0.0", home=home) == ["bash", "fish"]

    def test_empty_when_nothing_installed(self, home):
        """The post-command nudge must stay silent for anyone who never opted
        into completion."""
        assert completion.stale_shells("10.0.0", home=home) == []

    def test_empty_when_current(self, home):
        install("bash", SCRIPT, edit_rc=False, home=home)
        assert completion.stale_shells("9.9.9", home=home) == []


# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------


class TestInstall:
    def test_writes_script_and_reports_it(self, home):
        outcome = install("bash", SCRIPT, edit_rc=True, home=home)
        assert outcome.script_written is True
        assert outcome.script_path.read_text() == SCRIPT

    def test_rerun_with_identical_script_is_a_noop(self, home):
        install("bash", SCRIPT, edit_rc=True, home=home)
        outcome = install("bash", SCRIPT, edit_rc=True, home=home)
        assert outcome.script_written is False
        assert outcome.rc_line_added is False

    def test_rc_line_added_once_across_repeated_installs(self, home):
        for _ in range(3):
            install("bash", SCRIPT, edit_rc=True, home=home)
        rc = (home / ".bashrc").read_text()
        # The `>> ~/.bashrc` form this replaces duplicated the whole script on
        # every run; the whole point of the indirection is that this stays 1.
        # Counted by marker, not by path: the loader line names the path twice
        # (`[ -f "..." ] && source "..."`).
        assert rc.count("# remo shell completion") == 1
        assert len([ln for ln in rc.splitlines() if "completion.bash" in ln]) == 1

    def test_without_consent_the_rc_is_never_touched(self, home):
        rc = home / ".bashrc"
        rc.write_text("# untouched\n")
        outcome = install("bash", SCRIPT, edit_rc=False, home=home)
        assert rc.read_text() == "# untouched\n"
        assert outcome.rc_line_added is False
        # The caller gets the line to print so the user can add it by hand.
        assert outcome.pending_source_line is not None
        assert str(outcome.script_path) in outcome.pending_source_line

    def test_existing_rc_reference_suppresses_both_edit_and_prompt(self, home):
        """A hand-written or older-format loader line still counts as wired up
        — matching on the path, not the exact wording, avoids a duplicate."""
        layout = layout_for("bash", home=home)
        (home / ".bashrc").write_text(f". {layout.script_path}  # hand-rolled\n")
        outcome = install("bash", SCRIPT, edit_rc=True, home=home)
        assert outcome.rc_line_added is False
        assert outcome.pending_source_line is None

    def test_appends_to_rc_lacking_trailing_newline(self, home):
        """Appending to a file whose last line is unterminated must not weld
        the loader onto the end of the user's last command."""
        (home / ".bashrc").write_text("export FOO=1")
        install("bash", SCRIPT, edit_rc=True, home=home)
        lines = (home / ".bashrc").read_text().splitlines()
        assert lines[0] == "export FOO=1"

    def test_missing_rc_is_created(self, home):
        assert not (home / ".bashrc").exists()
        install("bash", SCRIPT, edit_rc=True, home=home)
        assert "completion.bash" in (home / ".bashrc").read_text()

    def test_fish_install_touches_no_rc(self, home):
        outcome = install("fish", SCRIPT, edit_rc=True, home=home)
        assert outcome.script_path.exists()
        assert outcome.rc_path is None
        assert outcome.rc_line_added is False
        assert outcome.pending_source_line is None


# ---------------------------------------------------------------------------
# staleness
# ---------------------------------------------------------------------------


class TestStaleness:
    def test_reads_the_stamped_version(self, home):
        install("bash", SCRIPT, edit_rc=False, home=home)
        assert installed_version("bash", home=home) == "9.9.9"

    def test_unstamped_script_reads_as_unknown(self, home):
        """Scripts generated by remo <= 2.2.0 carry no stamp. Unknown is
        treated as stale, which is the safe direction: the nudge is cheap and
        those are exactly the files that break."""
        install("bash", "_remo() { :; }\n", edit_rc=False, home=home)
        assert installed_version("bash", home=home) is None
        assert is_stale("bash", "9.9.9", home=home) is True

    def test_matching_version_is_not_stale(self, home):
        install("bash", SCRIPT, edit_rc=False, home=home)
        assert is_stale("bash", "9.9.9", home=home) is False

    def test_older_version_is_stale(self, home):
        install("bash", SCRIPT, edit_rc=False, home=home)
        assert is_stale("bash", "10.0.0", home=home) is True

    def test_absent_script_is_not_stale(self, home):
        """Someone who never installed completion should never be nudged about
        it — absent is not stale, it is uninterested."""
        assert is_stale("bash", "9.9.9", home=home) is False
        assert installed_version("bash", home=home) is None
