"""Shell-completion installation, layout, and staleness detection.

Python packaging has no post-install hook — a wheel is a zip archive
extracted onto disk, and pip/uv build a wheel even from an sdist, so there is
no point at which remo could write an activation script automatically. This
module is the substitute: an explicit ``remo completion install`` that any
install path (``uv tool install``, ``pipx``, ``install.sh``) can call.

Two design choices worth stating, because both are load-bearing:

**Drop-in files, not rc-file dumps.** Every shell gets its script written to
its own file; bash and zsh additionally get a single ``source`` line in their
rc. The obvious alternative — ``remo completion bash >> ~/.bashrc`` — is not
idempotent: running it twice leaves two copies of the script, which violates
Principle VII and makes upgrading a manual edit. With the indirection, an
upgrade rewrites one file and the rc line never moves.

**$SHELL, not the parent process.** Which rc file to edit is a question about
the user's *configured* login shell, not whichever subshell happens to be
running remo right now. Parent-process inspection is more accurate for "what
am I typing into" and wrong for "what should I persist to" — and it actively
misfires under ``curl | bash`` installers, where the parent is always bash.
"""

from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from remo_cli.core.config import get_remo_home_readonly

SHELLS: tuple[str, ...] = ("bash", "zsh", "fish")

# Matches the header written by cli/main.py::completion_header. Kept as a
# loose match on purpose: an older stamp with different surrounding wording
# should still yield its version rather than read as "no stamp at all".
# The header ends the sentence with a period, which \S+ would otherwise
# capture — hence the rstrip in installed_version().
_STAMP_RE = re.compile(r"generated by remo (\S+)")


@dataclass(frozen=True)
class ShellLayout:
    """Where a shell's activation script lives and how it gets loaded."""

    shell: str
    script_path: Path
    # None for fish: ~/.config/fish/completions/ is a native drop-in directory
    # that fish scans on its own, so there is nothing to edit.
    rc_path: Path | None
    source_line: str | None


def fish_config_dir(home: Path) -> Path:
    """Mirror fish's own config-directory resolution.

    fish uses ``$XDG_CONFIG_HOME/fish`` when that variable is set and
    ``~/.config/fish`` otherwise. Hardcoding the latter writes the script
    somewhere fish never reads, and fish's way of reporting that is to silently
    complete filenames instead — indistinguishable, from the user's seat, from
    a script that is simply broken. Getting this wrong is invisible until
    someone reports "tab gives me a file listing".
    """
    xdg = os.environ.get("XDG_CONFIG_HOME")
    return Path(xdg) / "fish" if xdg else home / ".config" / "fish"


def layout_for(shell: str, *, home: Path | None = None) -> ShellLayout:
    """Return the on-disk layout for ``shell``.

    ``home`` exists for tests; production callers use the real home directory.
    """
    if shell not in SHELLS:
        raise ValueError(f"Unsupported shell: {shell}")

    home = home or Path.home()

    if shell == "fish":
        return ShellLayout(
            shell="fish",
            script_path=fish_config_dir(home) / "completions" / "remo.fish",
            rc_path=None,
            source_line=None,
        )

    script_path = get_remo_home_readonly() / f"completion.{shell}"
    rc_name = ".bashrc" if shell == "bash" else ".zshrc"
    # Absolute, resolved path rather than ~ or $HOME: REMO_HOME/XDG_CONFIG_HOME
    # may point somewhere else entirely, and a wrong source line fails silently
    # at shell startup.
    return ShellLayout(
        shell=shell,
        script_path=script_path,
        rc_path=home / rc_name,
        source_line=f'[ -f "{script_path}" ] && source "{script_path}"',
    )


@dataclass(frozen=True)
class ShellDetection:
    """What shell we think the user is in, and how confident we should sound."""

    shell: str | None
    # "parent process" or "$SHELL" — surfaced to the user, because a detection
    # they can't see the basis of is one they can't correct.
    source: str
    # The other candidate when the two disagree. macOS ships zsh as the login
    # shell and many fish users launch fish from their terminal emulator
    # instead of via chsh, so $SHELL says zsh while they type into fish. That
    # disagreement is common enough to report rather than silently resolve.
    conflict: str | None = None


def _shell_from_env() -> str | None:
    name = Path(os.environ.get("SHELL", "")).name
    return name if name in SHELLS else None


def _ps_field(pid: int, field: str) -> str | None:
    """Read one ps field for ``pid``. Returns None on any failure.

    Uses ps rather than /proc so this works on macOS, where the whole
    login-shell-vs-interactive-shell mismatch is most common.
    """
    try:
        proc = subprocess.run(
            ["ps", "-p", str(pid), "-o", field],
            capture_output=True,
            text=True,
            timeout=2,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.strip() or None


def _shell_from_parent(max_depth: int = 5) -> str | None:
    """Walk up the process tree looking for a shell remo can complete for.

    Answers "what am I being typed into", which is the question that actually
    matters here — unlike $SHELL, which answers "what is configured as the
    login shell". Walks rather than checking only the immediate parent because
    console-script shims and `uv tool` wrappers can sit in between.
    """
    pid: int | None = os.getppid()
    for _ in range(max_depth):
        if pid is None or pid <= 1:
            return None
        comm = _ps_field(pid, "comm=")
        if comm is None:
            return None
        # Login shells appear as "-fish"/"-zsh"; ps may give a full path.
        name = Path(comm).name.lstrip("-")
        if name in SHELLS:
            return name
        ppid = _ps_field(pid, "ppid=")
        pid = int(ppid) if ppid and ppid.isdigit() else None
    return None


def detect_shell() -> ShellDetection:
    """Best-effort detection of the shell the user is actually working in.

    Parent process first, ``$SHELL`` as fallback. An earlier version consulted
    only ``$SHELL``, reasoning that "which rc file do I edit" is a question
    about the configured login shell. That holds for the rc edit and is wrong
    for the question that matters — on macOS it confidently installs zsh
    completion for someone sitting in fish, and reports success.
    """
    from_parent = _shell_from_parent()
    from_env = _shell_from_env()

    if from_parent is not None:
        conflict = from_env if from_env and from_env != from_parent else None
        return ShellDetection(from_parent, "parent process", conflict)
    return ShellDetection(from_env, "$SHELL")


def stale_shells(current_version: str, *, home: Path | None = None) -> list[str]:
    """Every shell with an installed completion script this remo did not write.

    Checks all shells rather than detecting one: this feeds the nudge that runs
    after every command, where the process-tree walk would be far too costly,
    and "which shell is stale" is answerable by three stat calls anyway.
    """
    return [s for s in SHELLS if is_stale(s, current_version, home=home)]


def installed_version(shell: str, *, home: Path | None = None) -> str | None:
    """Return the remo version stamped into the installed script, if any.

    None means either no script is installed or it predates version stamping
    (remo <= 2.2.0) — both are "cannot confirm it is current", which is what
    callers act on.
    """
    path = layout_for(shell, home=home).script_path
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:400]
    except OSError:
        return None
    m = _STAMP_RE.search(head)
    return m.group(1).rstrip(".") if m else None


def is_stale(shell: str, current_version: str, *, home: Path | None = None) -> bool:
    """True when a script is installed but was not generated by this remo.

    Absent script is not stale — the user never opted in, and nagging someone
    into a feature they did not ask for is worse than staying quiet.
    """
    if not layout_for(shell, home=home).script_path.exists():
        return False
    return installed_version(shell, home=home) != current_version


@dataclass(frozen=True)
class InstallOutcome:
    """What ``install`` actually did, so the CLI can report it accurately."""

    script_path: Path
    script_written: bool
    rc_path: Path | None
    rc_line_added: bool
    # Set when the rc line is needed but was not written, so the CLI can print
    # it for the user to add by hand.
    pending_source_line: str | None


def install(
    shell: str,
    source: str,
    *,
    edit_rc: bool,
    home: Path | None = None,
) -> InstallOutcome:
    """Write ``source`` to ``shell``'s drop-in path; optionally wire up the rc.

    Idempotent by construction (Principle VII): rewriting an identical script
    reports ``script_written=False``, and the rc line is appended only when an
    equivalent one is not already present.
    """
    layout = layout_for(shell, home=home)

    layout.script_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        unchanged = layout.script_path.read_text(encoding="utf-8") == source
    except OSError:
        unchanged = False
    if not unchanged:
        layout.script_path.write_text(source, encoding="utf-8")

    if layout.rc_path is None or layout.source_line is None:
        return InstallOutcome(
            script_path=layout.script_path,
            script_written=not unchanged,
            rc_path=None,
            rc_line_added=False,
            pending_source_line=None,
        )

    if _rc_references_script(layout):
        return InstallOutcome(
            script_path=layout.script_path,
            script_written=not unchanged,
            rc_path=layout.rc_path,
            rc_line_added=False,
            pending_source_line=None,
        )

    if not edit_rc:
        return InstallOutcome(
            script_path=layout.script_path,
            script_written=not unchanged,
            rc_path=layout.rc_path,
            rc_line_added=False,
            pending_source_line=layout.source_line,
        )

    _append_source_line(layout)
    return InstallOutcome(
        script_path=layout.script_path,
        script_written=not unchanged,
        rc_path=layout.rc_path,
        rc_line_added=True,
        pending_source_line=None,
    )


def _rc_references_script(layout: ShellLayout) -> bool:
    """True when the rc file already loads the drop-in script.

    Matches on the script path rather than the exact line: a user who
    hand-edited the wording, or who installed under an older line format,
    should not get a duplicate appended.
    """
    assert layout.rc_path is not None
    try:
        return str(layout.script_path) in layout.rc_path.read_text(
            encoding="utf-8", errors="replace"
        )
    except OSError:
        return False


def _append_source_line(layout: ShellLayout) -> None:
    assert layout.rc_path is not None and layout.source_line is not None
    existing = ""
    try:
        existing = layout.rc_path.read_text(encoding="utf-8")
    except OSError:
        pass

    prefix = "" if not existing or existing.endswith("\n") else "\n"
    block = f"{prefix}\n# remo shell completion\n{layout.source_line}\n"

    layout.rc_path.parent.mkdir(parents=True, exist_ok=True)
    with layout.rc_path.open("a", encoding="utf-8") as fh:
        fh.write(block)
